### ISSUE TITLE
Issues of evaluate code

### ISSUE THREAD

**Issue by heng94** [art-programmer/PlaneNet#10]
Hi ,
when I run the evaluate.py , There is only " gt" result , no "prediction " result .What code should I modify to get the "prediction" result ! Thanks

**Comment by bertjiazheng** [comment]
I have the same issue, is anyone able to solve it?

**Comment by DRAhmadFaraz** [comment]
@HanochZzhou @bertjiazheng Can you show your  gt" results screenshot.?
let me help you then.

**Comment by bertjiazheng** [comment]
Hi, @DRAhmadFaraz, I have got the predictions of PlaneNet, but the per-pixel recall seems to be lower than that in the paper. Can you reproduce the evaluation in the paper?  

Here are the results
Per-Pixel Recall: [0.        , 0.11259292, 0.39307635, 0.50202066, 0.53868158, 0.55395703, 0.57877339, 0.57877339, 0.60665465, 0.60665465, 0.60665465, 0.62022231, 0.62022231]
Per-Plane Recall: [0.  , 0.16, 0.32, 0.36, 0.38, 0.42, 0.46, 0.46, 0.48, 0.48, 0.48, 0.5 , 0.5 ]

**Comment by jcliu0428** [comment]
I have the same issue.Everyone knows how to fix it?

**Comment by jcliu0428** [comment]
I have the same issue.Anyone knows how to fix it?

**Comment by jcliu0428** [comment]
@bertjiazheng Have you got the prediction result in your 'evaluate folder'? Did you fix your command line to run evaluate.py? Thanks.

**Comment by bertjiazheng** [comment]
@jcliu0428 

Run with command line: 

`python evaluate.py --dataFolder=*** --numImages=760 --methods=2000000 --numOutputPlanes=10`

**Comment by jcliu0428** [comment]
@bertjiazheng Have you change anything in checkpoint.ckpt?
When I try your command line,it shows that:
InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on checkpoint/planenet_hybrid3_bl0_dl0_ll1_pb_pp_ps_sm0/checkpoint.ckpt: Not found: checkpoint/planenet_hybrid3_bl0_dl0_ll1_pb_pp_ps_sm0; No such file or directory

**Comment by bertjiazheng** [comment]
@jcliu0428  You don't need to modify anything. Make sure the `methods=2000000`, `0` will disable the corresponding method.

**Comment by jcliu0428** [comment]
@bertjiazheng I modify ALL_METHODS,it also works.Thanks a lot!

**Comment by XYZ-qiyh** [comment]
Hello, I'm confused about the `python evaluate.py` output result
![evaluate_output](https://user-images.githubusercontent.com/45621782/52989720-b07bd400-343f-11e9-821c-1c5d27eb6d63.png)
what does this mean?
Emm, where should I find the recall ?
@bertjiazheng @art-programmer Thanks a lot~

**Comment by bertjiazheng** [comment]
@Qtodd you can find the pixel recall [here](https://github.com/art-programmer/PlaneNet/blob/master/evaluate.py#L629) and plane recall [here](https://github.com/art-programmer/PlaneNet/blob/master/evaluate.py#L632).

**Comment by Qtodd** [comment]
@bertjiazheng sorry to bother you again
when I run the command line: 
`python evaluate.py --dataFolder=*** --numImages=760 --methods=2000000 --numOutputPlanes=10`
it show that:
Traceback (most recent call last):
  File "evaluate.py", line 1747, in <module>
    evaluatePlanes(args)
  File "evaluate.py", line 538, in evaluatePlanes
    plotResults(gt_dict, predictions, options)  
  File "evaluate.py", line 691, in plotResults
    plotCurvesSplit(xs[metric_index], curves, filenames = [filename + '.png', filename + '_oracle.png'], xlabel=xlabels[metric_index], ylabel='Per-pixel recall', title=curve_titles[metric_index], labels=curve_labels)
  File "/home/Qtodd/Plane/PlaneNet/utils.py", line 2337, in **plotCurvesSplit**
    plt.plot(x, ys[order], figure=fig, label=final_labels[order], color=colors[order], marker=markers[order], linewidth=sizes[order])
**IndexError: list index out of range**

**Comment by XYZ-qiyh** [comment]
Hey, when I run the evaluate.py, I only got the prediction of PlaneNet.  
What can I do to get the results of other existing methods ?? @jcliu0428 @bertjiazheng

**Comment by skq-5233** [comment]
Why is there no quantitative comparison output when I run evaluate.py?Looking forward to your reply. Thank you!@bertjiazheng

**Comment by skq-5233** [comment]
> Hi, @DRAhmadFaraz, I have got the predictions of PlaneNet, but the per-pixel recall seems to be lower than that in the paper. Can you reproduce the evaluation in the paper?
> 
> Here are the results
> Per-Pixel Recall: [0. , 0.11259292, 0.39307635, 0.50202066, 0.53868158, 0.55395703, 0.57877339, 0.57877339, 0.60665465, 0.60665465, 0.60665465, 0.62022231, 0.62022231]
> Per-Plane Recall: [0. , 0.16, 0.32, 0.36, 0.38, 0.42, 0.46, 0.46, 0.48, 0.48, 0.48, 0.5 , 0.5 ]

Hello, when I run python evaluate.py, I do not know what the reason is and do not output quantitative results such as rel, rmse, etc. I hope you take the time to reply to me. Thank you!

**Comment by skq-5233** [comment]
Hello, when I run python evaluate.py, I do not know what the reason is and do not output quantitative results such as rel, rmse, etc. I hope you take the time to reply to me. Thank you!
@bertjiazheng

**Comment by skq-5233** [comment]
> Hey, when I run the evaluate.py, I only got the prediction of PlaneNet.
> What can I do to get the results of other existing methods ?? @jcliu0428 @bertjiazheng

Hello, why do I run the test code: python evaluate.py --dataFolder="./data" --numImages=760 --methods=2000000 --numOutputPlanes=10, there is no quantitative result output (such as rel, rmse, etc.)? Hope you take the time to reply! ! Thank you very much! ! !

**Comment by skq-5233** [comment]
> @HanochZzhou @bertjiazheng Can you show your gt" results screenshot.?
> let me help you then.
Hello, when I run python evaluate.py, I do not know what the reason is and do not output quantitative results such as rel, rmse, etc. I hope you take the time to reply to me. Thank you!

**Comment by skq-5233** [comment]
> Hello, I'm confused about the `python evaluate.py` output result
> ![evaluate_output](https://user-images.githubusercontent.com/45621782/52989720-b07bd400-343f-11e9-821c-1c5d27eb6d63.png)
> what does this mean?
> Emm, where should I find the recall ?
> @bertjiazheng @art-programmer Thanks a lot~

Hello, you run the test code: python evaluate.py Is there quantitative output (such as rel, rmse, etc.)? Hope you take the time to reply! ! Thank you very much! ! !

**Comment by skq-5233** [comment]
> Hi ,
> when I run the evaluate.py , There is only " gt" result , no "prediction " result .What code should I modify to get the "prediction" result ! Thanks

Hello, you run the test code: python evaluate.py Is there quantitative output (such as rel, rmse, etc.)? Hope you take the time to reply! ! Thank you very much! ! !
