### ISSUE TITLE
Issue of Evaluation Code

### ISSUE THREAD

**Issue by sam8214** [art-programmer/PlaneNet#24]
After applying the evaluate.py The following error appeared: ValueError: operands could not be broadcast together with shapes (192,256,20,10) (192,256,20,20)

Traceback (most recent call last):
  File "evaluate.py", line 1716, in <module>
    evaluatePlanes(args)
  File "evaluate.py", line 528, in evaluatePlanes
    plotResults(gt_dict, predictions, options)
  File "evaluate.py", line 594, in plotResults
    pixelStatistics, planeStatistics = evaluatePlanePrediction(predDepths, segmentations[image_index], predNumPlanes, gtDepths, gt_dict['segmentation'][image_index], gt_dict['num_planes'][image_index])
  File "/home/samuel/Downloads/PlaneNet-master/utils.py", line 2136, in evaluatePlanePrediction
    planeDiffs = np.abs(depthDiffs * intersectionMask).sum(axis=(0, 1)) / np.maximum(intersection, 1e-4)

**Comment by wullish** [comment]
How did you solve your problem? I'm getting this error:

```
File "evaluate.py", line 15, in <module>
    from utils import *
  File "/home/ec2-user/SageMaker/PlaneNet/utils.py", line 981
    return
         ^
TabError: inconsistent use of tabs and spaces in indentation"
```

**Comment by JiaXuanWang** [comment]
Hi, I have the same issue, did you find a solution for it? @sam8214

**Comment by Navyatr13** [comment]
Hey Sam, I am facing the same issue. Can you help me if you have solved this problem.
