### ISSUE TITLE
About the format of the trained model

### ISSUE THREAD

**Issue by xiaoyangl9413** [art-programmer/PlaneNet#8]
Hi author,
Your job is amazing. But I have some doubts on your trained model format. You only have checkpoint(.ckpt) file inside the sample_np10_hybrid3_bl0_dl0_ds0_crfrnn5_sm0 folder. I'm wondering could you include tf.GraphDef (.pb) as well? In this way we might be able to do freeze graph things.

Thank you!

**Comment by art-programmer** [comment]
Thank you for your interests in our work. Correct me if I am wrong but I think you should be able to do freeze graph things with the checkpoint file (.ckpt) as shown here,

https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py

**Comment by xiaoyangl9413** [comment]
Thank you for your quick response.
My understanding is if we want to do freeze graph, we first need to get a graph representation(.pb/.pbtxt) from weight during trainning stage(.ckpt). And then we can call freeze_graph.py to encapsulate both the weight and the graph into another frozen DefGraph structure.
In the example that you gave, it seems like very vague on how to do the first step(checkpoint -> unfrozen graph). I still have no clue how to convert your .ckpt files into the graph which is the first step. Do you have any idea how to do it?

Thanks!

**Comment by xiaoyangl9413** [comment]
Thank you for your quick response.
I guess right now my issue is that I cannot do 
`tf.train.import_meta_graph("checkpoint/sample_np10_hybrid3_bl0_dl0_ds0_crfrnn5_sm0/checkpoint.ckpt.meta")`
The error is 
`Traceback (most recent call last):
  File "writeGraph.py", line 24, in <module>
    loader = tf.train.import_meta_graph("/home/xiaoyang/project/PlaneNet/checkpoint/sample_np10_hybrid3_bl0_dl0_ds0_crfrnn5_sm0/checkpoint.ckpt.meta")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1941, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: u'HighDimFilter'`

Do you have any idea why this is happening?


Thank you

**Comment by xiaoyangl9413** [comment]
@art-programmer

**Comment by art-programmer** [comment]
I guess it's due to the fact that HighDimFilter is from a compiled C++ library. I don't know how to freeze that part though.
